"
Examples for using PDFtalk
"
Class {
	#name : #AboutPDFtalkDemonstrations,
	#superclass : #Object,
	#category : #'PDFtalk-Demonstrations'
}

{ #category : #properties }
AboutPDFtalkDemonstrations class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> creationTime [
	^'21.06.2022 08:32:19'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> isFunctional [
	^true
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> source [
	^'Package [PDFtalk Demonstrations](2.5.0.3,chaider)'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> sourceTime [
	^'28.07.2021 16:00:17'
]

{ #category : #properties }
AboutPDFtalkDemonstrations class >> targetSmalltalk [
	^'Pharo 10.0'
]
