"
Parsing PDF source
"
Class {
	#name : #AboutPDFtalkParsing,
	#superclass : #Object,
	#category : #'PDFtalk-Parsing'
}

{ #category : #properties }
AboutPDFtalkParsing class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkParsing class >> creationTime [
	^'21.06.2022 08:32:08'
]

{ #category : #properties }
AboutPDFtalkParsing class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkParsing class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkParsing class >> source [
	^'Package [PDFtalk Parsing](2.5.0.2,chaider)'
]

{ #category : #properties }
AboutPDFtalkParsing class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkParsing class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkParsing class >> sourceTime [
	^'28.07.2021 16:00:43'
]

{ #category : #properties }
AboutPDFtalkParsing class >> targetSmalltalk [
	^'Pharo 10.0'
]
