"
Implementation of the OpenType specification

(see http://www.microsoft.com/typography/otspec/default.htm for specifications)
"
Class {
	#name : #AboutPDFtalkFontsOpenType,
	#superclass : #Object,
	#category : #'PDFtalk-Fonts OpenType'
}

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> creationTime [
	^'21.06.2022 08:32:11'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> source [
	^'Package [PDFtalk Fonts OpenType](2.5.3.4,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> sourceTime [
	^'18.05.2022 10:30:29'
]

{ #category : #properties }
AboutPDFtalkFontsOpenType class >> targetSmalltalk [
	^'Pharo 10.0'
]
