"
the runtime code for the Adobe Type 1 font format
"
Class {
	#name : #AboutPDFtalkFontsType1,
	#superclass : #Object,
	#category : #'PDFtalk-Fonts Type1'
}

{ #category : #properties }
AboutPDFtalkFontsType1 class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> creationTime [
	^'21.06.2022 08:32:10'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> source [
	^'Package [PDFtalk Fonts Type1](2.5.5.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> sourceTime [
	^'21.06.2022 04:50:01'
]

{ #category : #properties }
AboutPDFtalkFontsType1 class >> targetSmalltalk [
	^'Pharo 10.0'
]
