"
Example objects for test purposes
"
Class {
	#name : #AboutPDFtalkTestResources,
	#superclass : #Object,
	#category : #'PDFtalk-test resources'
}

{ #category : #properties }
AboutPDFtalkTestResources class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> creationTime [
	^'21.06.2022 08:32:17'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkTestResources class >> source [
	^'Package [PDFtalk test resources](2.5.0.5,chaider)'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> sourceTime [
	^'28.07.2021 16:00:24'
]

{ #category : #properties }
AboutPDFtalkTestResources class >> targetSmalltalk [
	^'Pharo 10.0'
]
