"
Objects of the PDF file structure (PDF 32000_2008.pdf pp. 38)
"
Class {
	#name : #AboutPDFtalkFiles,
	#superclass : #Object,
	#category : #'PDFtalk-Files'
}

{ #category : #properties }
AboutPDFtalkFiles class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkFiles class >> creationTime [
	^'21.06.2022 08:32:14'
]

{ #category : #properties }
AboutPDFtalkFiles class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFiles class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkFiles class >> source [
	^'Package [PDFtalk Files](2.5.0.3,chaider)'
]

{ #category : #properties }
AboutPDFtalkFiles class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkFiles class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkFiles class >> sourceTime [
	^'28.07.2021 16:00:35'
]

{ #category : #properties }
AboutPDFtalkFiles class >> targetSmalltalk [
	^'Pharo 10.0'
]
