"
Basic objects for reading a PDF
"
Class {
	#name : #AboutPDFtalkBasics,
	#superclass : #Object,
	#category : #'PDFtalk-Basics'
}

{ #category : #properties }
AboutPDFtalkBasics class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasics class >> creationTime [
	^'21.06.2022 08:32:07'
]

{ #category : #properties }
AboutPDFtalkBasics class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasics class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkBasics class >> source [
	^'Package [PDFtalk Basics](2.5.3.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasics class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkBasics class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkBasics class >> sourceTime [
	^'03.04.2022 17:29:55'
]

{ #category : #properties }
AboutPDFtalkBasics class >> targetSmalltalk [
	^'Pharo 10.0'
]
