"
PDF Stream objects as defined in PDF 32000_2008.pdf section 7.3.8, pp. 19

"
Class {
	#name : #AboutPDFtalkStreams,
	#superclass : #Object,
	#category : #'PDFtalk-Streams'
}

{ #category : #properties }
AboutPDFtalkStreams class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkStreams class >> creationTime [
	^'21.06.2022 08:32:08'
]

{ #category : #properties }
AboutPDFtalkStreams class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkStreams class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkStreams class >> source [
	^'Package [PDFtalk Streams](2.5.5.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkStreams class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkStreams class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkStreams class >> sourceTime [
	^'21.06.2022 04:50:16'
]

{ #category : #properties }
AboutPDFtalkStreams class >> targetSmalltalk [
	^'Pharo 10.0'
]
