"
PDF Images as defined in PDF 32000_2008.pdf, section 8.9, pp. 203.

PDF’s painting operators include general facilities for dealing with sampled images. A sampled image (or just image for short) is a rectangular array of sample values, each representing a colour. The image may approximate the appearance of some natural scene obtained through an input scanner or a video camera, or it may be generated synthetically
"
Class {
	#name : #AboutPDFtalkImages,
	#superclass : #Object,
	#category : #'PDFtalk-Images'
}

{ #category : #properties }
AboutPDFtalkImages class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkImages class >> creationTime [
	^'21.06.2022 08:32:14'
]

{ #category : #properties }
AboutPDFtalkImages class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkImages class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkImages class >> source [
	^'Package [PDFtalk Images](2.5.0.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkImages class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkImages class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkImages class >> sourceTime [
	^'14.06.2021 10:44:57'
]

{ #category : #properties }
AboutPDFtalkImages class >> targetSmalltalk [
	^'Pharo 10.0'
]
