"
PDF Objects (PDF 32000_2008.pdf pp. 13)
"
Class {
	#name : #AboutPDFtalkBasicObjects,
	#superclass : #Object,
	#category : #'PDFtalk-Basic Objects'
}

{ #category : #properties }
AboutPDFtalkBasicObjects class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> creationTime [
	^'21.06.2022 08:32:07'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> source [
	^'Package [PDFtalk Basic Objects](2.5.4.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> sourceTime [
	^'11.06.2022 04:46:54'
]

{ #category : #properties }
AboutPDFtalkBasicObjects class >> targetSmalltalk [
	^'Pharo 10.0'
]
