"
PDF Shading Pattern as defined in PDF 32000_2008.pdf, section 8.7.4, pp. 181

Shading patterns (PDF 1.3) provide a smooth transition between colours across an area to be painted, independent of the resolution of any particular output device and without specifying the number of steps in the colour transition. Patterns of this type shall be described by pattern dictionaries with a pattern type of 2.
"
Class {
	#name : #AboutPDFtalkShading,
	#superclass : #Object,
	#category : #'PDFtalk-Shading'
}

{ #category : #properties }
AboutPDFtalkShading class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkShading class >> creationTime [
	^'21.06.2022 08:32:15'
]

{ #category : #properties }
AboutPDFtalkShading class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkShading class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkShading class >> source [
	^'Package [PDFtalk Shading](2.3.4.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkShading class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkShading class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkShading class >> sourceTime [
	^'27.09.2020 18:55:07'
]

{ #category : #properties }
AboutPDFtalkShading class >> targetSmalltalk [
	^'Pharo 10.0'
]
