"
Objects of the PDF Document structure (PDF 32000_2008.pdf pp. 70)
"
Class {
	#name : #AboutPDFtalkDocument,
	#superclass : #Object,
	#category : #'PDFtalk-Document'
}

{ #category : #properties }
AboutPDFtalkDocument class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkDocument class >> creationTime [
	^'21.06.2022 08:32:14'
]

{ #category : #properties }
AboutPDFtalkDocument class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkDocument class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkDocument class >> source [
	^'Package [PDFtalk Document](2.5.0.5,chaider)'
]

{ #category : #properties }
AboutPDFtalkDocument class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkDocument class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkDocument class >> sourceTime [
	^'28.07.2021 16:00:32'
]

{ #category : #properties }
AboutPDFtalkDocument class >> targetSmalltalk [
	^'Pharo 10.0'
]
