"
namespace and common protocol for all external font types
"
Class {
	#name : #AboutPDFtalkFontsBasics,
	#superclass : #Object,
	#category : #'PDFtalk-Fonts Basics'
}

{ #category : #properties }
AboutPDFtalkFontsBasics class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> creationTime [
	^'21.06.2022 08:32:10'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> source [
	^'Package [PDFtalk Fonts Basics](2.4.0.3,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> sourceTime [
	^'23.03.2021 07:17:37'
]

{ #category : #properties }
AboutPDFtalkFontsBasics class >> targetSmalltalk [
	^'Pharo 10.0'
]
