"
rendering to create a Document
"
Class {
	#name : #AboutPDFtalkRendering,
	#superclass : #Object,
	#category : #'PDFtalk-Rendering'
}

{ #category : #properties }
AboutPDFtalkRendering class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkRendering class >> creationTime [
	^'21.06.2022 08:32:15'
]

{ #category : #properties }
AboutPDFtalkRendering class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkRendering class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkRendering class >> source [
	^'Package [PDFtalk Rendering](2.5.1.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkRendering class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkRendering class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkRendering class >> sourceTime [
	^'08.08.2021 11:35:04'
]

{ #category : #properties }
AboutPDFtalkRendering class >> targetSmalltalk [
	^'Pharo 10.0'
]
