"
Objects of chapter 12: Interactive Features (PDF 32000_2008.pdf pp. 362)

"
Class {
	#name : #AboutPDFtalkInteractiveFeatures,
	#superclass : #Object,
	#category : #'PDFtalk-Interactive Features'
}

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> creationTime [
	^'21.06.2022 08:32:15'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> source [
	^'Package [PDFtalk Interactive Features](2.5.0.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> sourceTime [
	^'14.06.2021 15:10:26'
]

{ #category : #properties }
AboutPDFtalkInteractiveFeatures class >> targetSmalltalk [
	^'Pharo 10.0'
]
