"
Tests
"
Class {
	#name : #AboutPDFtalkTests,
	#superclass : #Object,
	#category : #'PDFtalk-tests'
}

{ #category : #properties }
AboutPDFtalkTests class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkTests class >> creationTime [
	^'21.06.2022 08:32:18'
]

{ #category : #properties }
AboutPDFtalkTests class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkTests class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkTests class >> source [
	^'Package [PDFtalk tests](2.5.0.5,chaider)'
]

{ #category : #properties }
AboutPDFtalkTests class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkTests class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkTests class >> sourceTime [
	^'28.07.2021 16:00:20'
]

{ #category : #properties }
AboutPDFtalkTests class >> targetSmalltalk [
	^'Pharo 10.0'
]
