"
PDF Dictionary and Stream objects as defined in PDF 32000_2008.pdf pp. 18.
"
Class {
	#name : #AboutPDFtalkTyping,
	#superclass : #Object,
	#category : #'PDFtalk-Typing'
}

{ #category : #properties }
AboutPDFtalkTyping class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkTyping class >> creationTime [
	^'21.06.2022 08:32:07'
]

{ #category : #properties }
AboutPDFtalkTyping class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkTyping class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkTyping class >> source [
	^'Package [PDFtalk Typing](2.5.0.3,chaider)'
]

{ #category : #properties }
AboutPDFtalkTyping class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkTyping class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkTyping class >> sourceTime [
	^'20.07.2021 08:22:37'
]

{ #category : #properties }
AboutPDFtalkTyping class >> targetSmalltalk [
	^'Pharo 10.0'
]
