"
Tests for the basics of external font types

"
Class {
	#name : #AboutPDFtalkFontsTests,
	#superclass : #Object,
	#category : #'PDFtalk-Fonts tests'
}

{ #category : #properties }
AboutPDFtalkFontsTests class >> creationRules [
	^'Package [Pharo Fileout PDFtalk](1.3.1.1,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> creationTime [
	^'21.06.2022 08:32:18'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> creator [
	^'Bundle {Smalltalk Transform Project}(2.0.2.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> isFunctional [
	^false
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> source [
	^'Package [PDFtalk Fonts tests](2.3.0.0,chaider)'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> sourceSmalltalk [
	^'VisualWorks®, 9.2 of 7. Januar 2022'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> sourceStore [
	^'psql_public_cst_2007'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> sourceTime [
	^'06.02.2020 07:46:09'
]

{ #category : #properties }
AboutPDFtalkFontsTests class >> targetSmalltalk [
	^'Pharo 10.0'
]
